mixed-port: 7897
allow-lan: true
mode: rule
log-level: info

# 关闭自动下载, 避免新机器无代理死锁
geodata-mode: false
geox-url:
  geoip: "https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geoip.dat"
  geosite: "https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geosite.dat"

proxies:
  - name: "VLESS-Vision-Direct"
    type: vless
    server: gatewaynode11.xyz
    port: 443
    uuid: baedd174-2b70-48af-aa30-7d6fe8032511
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: gatewaynode11.xyz
    client-fingerprint: chrome

proxy-groups:
  - name: "Proxy"
    type: select
    proxies:
      - "VLESS-Vision-Direct"
      - "DIRECT"

rules:
  - DOMAIN,easytake.work,DIRECT
  - GEOIP,CN,DIRECT
  - DOMAIN-SUFFIX,baidu.com,DIRECT
  - DOMAIN-SUFFIX,bilibili.com,DIRECT
  - DOMAIN-SUFFIX,qq.com,DIRECT
  - DOMAIN-SUFFIX,weibo.com,DIRECT
  - DOMAIN-SUFFIX,alipay.com,DIRECT
  - MATCH,Proxy
